---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: webk8s:node-info-master
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: webk8s:node-info-master
subjects:
  - kind: ServiceAccount
    name: webk8s-master
    namespace: webk8s
