---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webk8s:node-info-master
rules:
  - apiGroups: [ "" ] # Core
    resources: [ "pods" ]
    verbs: [ "list" ]
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: [ "create", "delete" ]
