---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: webk8s
resources:
  - serviceaccount.yml
  - clusterrole.yml
  - clusterrolebinding.yml
  - deployment.yml
  - service.yml
